"""empty message

Revision ID: 000d09f987b1
Revises: 
Create Date: 2018-09-20 21:42:05.252357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000d09f987b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('general_description', sa.Text(), nullable=True),
    sa.Column('payment_description', sa.Text(), nullable=True),
    sa.Column('groups_description', sa.Text(), nullable=True),
    sa.Column('googlemaps_link', sa.Text(), nullable=True),
    sa.Column('paytrail_product', sa.String(length=11), nullable=True),
    sa.Column('email_template', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(), nullable=True),
    sa.Column('setting_value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('param', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('handled', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('realname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('distance', sa.Numeric(), nullable=True),
    sa.Column('price_prepay', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('number_prefix', sa.String(), nullable=True),
    sa.Column('tagrange_start', sa.Integer(), nullable=True),
    sa.Column('tagrange_end', sa.Integer(), nullable=True),
    sa.Column('racenumberrange_start', sa.Integer(), nullable=True),
    sa.Column('racenumberrange_end', sa.Integer(), nullable=True),
    sa.Column('current_tag', sa.Integer(), nullable=True),
    sa.Column('current_racenumber', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Numeric(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('streetaddress', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('payment_type', sa.Integer(), nullable=True),
    sa.Column('payment_confirmed', sa.Boolean(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('tagnumber', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('referencenumber', sa.Integer(), nullable=True),
    sa.Column('sport_voucher', sa.Boolean(), nullable=True),
    sa.Column('sport_voucher_name', sa.Text(), nullable=True),
    sa.Column('team', sa.Text(), nullable=True),
    sa.Column('jyps_member', sa.Boolean(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['event_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    op.drop_table('event_group')
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('settings')
    op.drop_table('event')
    op.drop_table('data')
    # ### end Alembic commands ###
