"""empty message

Revision ID: 11e5a815ff27
Revises: 9ec96b069aa4
Create Date: 2018-03-18 20:22:40.613069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e5a815ff27'
down_revision = '9ec96b069aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_group', sa.Column('current_racenumber', sa.Integer(), nullable=True))
    op.add_column('event_group', sa.Column('racenumberrange_end', sa.Integer(), nullable=True))
    op.add_column('event_group', sa.Column('racenumberrange_start', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_group', 'racenumberrange_start')
    op.drop_column('event_group', 'racenumberrange_end')
    op.drop_column('event_group', 'current_racenumber')
    # ### end Alembic commands ###
