"""empty message

Revision ID: 6e992b2fd1ec
Revises: 
Create Date: 2020-01-11 20:41:49.753057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e992b2fd1ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discount')
    op.drop_index('refnum', table_name='participant')
    op.drop_index('taskhandler', table_name='task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('taskhandler', 'task', ['status', 'type'], unique=False)
    op.create_index('refnum', 'participant', ['referencenumber'], unique=False)
    op.create_table('discount',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
