"""empty message

Revision ID: 9ec96b069aa4
Revises: 
Create Date: 2018-03-18 17:26:20.938012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec96b069aa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('general_description', sa.String(length=80), nullable=True),
    sa.Column('payment_description', sa.String(length=80), nullable=True),
    sa.Column('groups_description', sa.String(length=80), nullable=True),
    sa.Column('googlemaps_link', sa.String(length=250), nullable=True),
    sa.Column('paytrail_product', sa.String(length=11), nullable=True),
    sa.Column('email_template', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=True),
    sa.Column('value', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('realname', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('distance', sa.Numeric(), nullable=True),
    sa.Column('price_prepay', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('product_code', sa.String(length=80), nullable=True),
    sa.Column('number_prefix', sa.String(length=80), nullable=True),
    sa.Column('tagrange_start', sa.Integer(), nullable=True),
    sa.Column('tagrange_end', sa.Integer(), nullable=True),
    sa.Column('current_tag', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('streetaddress', sa.String(length=80), nullable=True),
    sa.Column('zipcode', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('telephone', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('club', sa.String(length=80), nullable=True),
    sa.Column('payment_type', sa.Integer(), nullable=True),
    sa.Column('payment_confirmed', sa.Boolean(), nullable=True),
    sa.Column('memo', sa.String(length=250), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('tagnumber', sa.String(length=80), nullable=True),
    sa.Column('number', sa.String(length=80), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['event_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    op.drop_table('event_group')
    op.drop_table('user')
    op.drop_table('settings')
    op.drop_table('event')
    op.drop_table('data')
    # ### end Alembic commands ###
