"""empty message

Revision ID: ecc10d0a94ca
Revises: ed2331982f45
Create Date: 2018-04-16 23:20:18.241060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc10d0a94ca'
down_revision = 'ed2331982f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('open_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'open_date')
    # ### end Alembic commands ###
