"""empty message

Revision ID: ed2331982f45
Revises: 96b13403a5d4
Create Date: 2018-04-15 22:42:00.434576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2331982f45'
down_revision = '96b13403a5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('close_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'close_date')
    # ### end Alembic commands ###
